### ISSUE TITLE
Documentation: incorrect Go version requirements

### ISSUE THREAD

**Issue by aval13** [sensu/sensu-go#4400]
In the README.md in the "Building from source" section, it is specified:
"You will first need Go 1.13.3 installed".
I believe this is incorrect since there are dependencies at this moment in the 6.4.0 release that require Go 1.16.

## Expected Behavior
Install Go 1.13.3+.
Compile should work.

## Current Behavior
sensu-backend does not build with go version higher than 1.13.3 but still in the 1.13.x series.
```
[...]
Selecting previously unselected package golang-1.13-go.
Preparing to unpack .../72-golang-1.13-go_1.13.8-1ubuntu1~18.04.3_amd64.deb ...
Unpacking golang-1.13-go (1.13.8-1ubuntu1~18.04.3) ...
[...]
go: finding sigs.k8s.io/yaml v1.2.0
# go.etcd.io/etcd/client/pkg/v3/tlsutil
/root/go/pkg/mod/go.etcd.io/etcd/client/pkg/v3@v3.5.0/tlsutil/cipher_suites.go:22:20: undefined: tls.CipherSuites
/root/go/pkg/mod/go.etcd.io/etcd/client/pkg/v3@v3.5.0/tlsutil/cipher_suites.go:27:20: undefined: tls.InsecureCipherSuites
/root/go/pkg/mod/go.etcd.io/etcd/client/pkg/v3@v3.5.0/tlsutil/cipher_suites.go:34:10: undefined: tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
/root/go/pkg/mod/go.etcd.io/etcd/client/pkg/v3@v3.5.0/tlsutil/cipher_suites.go:36:10: undefined: tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
note: module requires Go 1.16
# go.opentelemetry.io/otel/trace
/root/go/pkg/mod/go.opentelemetry.io/otel/trace@v0.20.0/config.go:117:2: duplicate method private
note: module requires Go 1.14
[...]
```

## Possible Solution
Update the documentation to specify Go 1.16.x is required.
Using Go 1.16.2 worked for me.

## Steps to Reproduce (for bugs)
Use a fully up-to-date Ubuntu 18.04 LTS.
Install golang-1.13 (comes with 1.13.8 which is higher than the 1.13.3 specified in docs).
Switch Go implementation from 1.10 (default) to 1.13.
Download the 6.4.0 release source code.
Run the build-from-source steps as specified in the documentation.

## Context
I was just trying to build from source 6.4.0 version release.

## Your Environment
Not a bug per-se, nothing to comment here, see the reproduce steps.

**Comment by echlebek** [comment]
Thanks, this is indeed a doc bug.

**Comment by echlebek** [comment]
I've updated the minimum Go version to Go 1.16.
